
name: Process and Store Data

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
  process-data:
    runs-on: ubuntu-latest

    services:
      mongodb:
        image: mongo
        ports:
        - 27017:27017

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.9'

    - name: Set up Python 3.9
      uses: actions/setup-python@v3
      with:
        python-version: 3.9
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install beautifulsoup4==4.12.3 certifi==2024.2.2 charset-normalizer==3.3.2 dnspython==2.6.1 idna==3.7 pymongo==4.7.2 PyYAML==6.0.1 requests==2.31.0 soupsieve==2.5 urllib3==2.2.1
      - name: Run the data extraction script
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          python app.py
    - name: Run Data Extraction Script
      env:
        MONGO_URL: mongodb://localhost:27017
        GITHUB_TOKEN: ${{ secrets.TOKEN }}
      run: |
        python app.py
      - name: Upload processed data
        uses: actions/upload-artifact@v3
        with:
          name: processed-data
          path: files_parsed1/
