name: Data Extraction and Storage Pipeline

on:
  workflow_dispatch:


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Set up Python 3.9
      uses: actions/setup-python@v3
      with:
        python-version: 3.9

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run Data Extraction Script
      env:
        MONGO_URL: ${{ secrets.URL_MONGO }}
        GITHUB_TOKEN: ${{ secrets.TOKEN }}
      run: |
        python app.py
