name: Process and Store Data

on:
  push:
    branches:
      - main

jobs:
  process-data:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run the data extraction script
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          python app.py

      - name: Upload processed data
        uses: actions/upload-artifact@v3
        with:
          name: processed-data
          path: files_parsed1/
